export const projectList = [
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
  {
    ProjectName: "bgmi",
    Reason: "enjoye",
    Type: "gaming",
    Division: "good",
    Category: "Quality A",
    Priority: "High",
    Dept: "frendly",
    Location: "jamkhed",
    Status: "Running",
  },
  {
    ProjectName: "coc",
    Reason: "timepass",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality B",
    Priority: "Mid",
    Dept: "Strategy",
    Location: "beed",
    Status: "Running",
  },
  {
    ProjectName: "Line filter",
    Reason: "mazboori",
    Type: "filter",
    Division: "help",
    Category: "Quality D",
    Priority: "Low",
    Dept: "Nice",
    Location: "asti",
    Status: "closed",
  },
  {
    ProjectName: "cod",
    Reason: "mazboori",
    Type: "gaming",
    Division: "compresser",
    Category: "Quality A",
    Priority: "Low",
    Dept: "Strategy",
    Location: "Pune",
    Status: "close",
  },
];
